{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled (not .Values.postgresql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "schautrack.postgresql.fullname" . }}
  labels:
    {{- include "schautrack.postgresql.labels" . | nindent 4 }}
    {{- with .Values.postgresql.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.postgresql.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  {{- if .Values.postgresql.persistence.storageClass }}
  {{- if eq .Values.postgresql.persistence.storageClass "-" }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
